# Numpy

#### 1.Создать вектор (одномерный массив) размера 100, заполненный нулями

In [6]:
import numpy as np

In [7]:
d = np.zeros(100)
print (d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


#### 2.Создать вектор размера 100, заполненный единицами

In [10]:
d = np.ones(100)
print (d)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


#### 3.Создать вектор размера 100, заполненный числом 3

In [11]:
d = np.full(100, 3)
print (d)

[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]


#### 4. Поменять 2 строки в матрице

In [31]:
d = np.arange(9).reshape(3,3)
print(d)
d[[0,1]] = d[[1,0]]
print(d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4 5]
 [0 1 2]
 [6 7 8]]


#### 5. Создать вектор со значениями от 10 до 100

In [9]:
d = np.arange(start=10, stop=101, step=1)
print(d)

[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]


#### 6. Создать матрицу (двумерный массив) 4x4 со значениями от 0 до 16

In [14]:
d = np.arange(16).reshape(4,4)
print(d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


#### 7. Создать 3x3 единичную матрицу

In [12]:
d = np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 8. Создать массив 3x3x3 со случайными значениями

In [32]:
d = np.random.random((3,3,3))
print(d)

[[[0.12880312 0.05409488 0.03275001]
  [0.93103261 0.76680165 0.74350705]
  [0.032515   0.54590661 0.70710784]]

 [[0.64321385 0.20698641 0.70204496]
  [0.09128862 0.92987219 0.09577837]
  [0.51737924 0.36049765 0.16469811]]

 [[0.6837133  0.35066153 0.82884408]
  [0.79244612 0.54911731 0.12010697]
  [0.99593898 0.21472812 0.04240452]]]


#### 9. Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [16]:
d = np.random.random((10,10))
dmin, dmax = d.min(), d.max()
print(d)
print(dmin, dmax)

[[0.4327188  0.54457961 0.46504837 0.47991221 0.98874334 0.78257704
  0.86827069 0.77320446 0.90280558 0.58624915]
 [0.42290799 0.64816431 0.31440881 0.69719577 0.85729204 0.20515115
  0.63624909 0.4006011  0.21413346 0.67224608]
 [0.96452423 0.77461426 0.35499598 0.94351389 0.99727264 0.08645521
  0.57264876 0.56312016 0.15419097 0.70830929]
 [0.87934066 0.36910715 0.79120983 0.12749391 0.6099825  0.09207357
  0.13707655 0.82885562 0.86243819 0.7376459 ]
 [0.83755157 0.83999787 0.8589822  0.38425362 0.01635535 0.77309143
  0.47761677 0.43584026 0.79399376 0.71538047]
 [0.84910683 0.41250309 0.49145666 0.4553214  0.130307   0.46098903
  0.02754911 0.23295571 0.61985688 0.97259717]
 [0.45305247 0.86449765 0.18970069 0.59350404 0.27785492 0.07098139
  0.95807832 0.14027077 0.14622949 0.06307145]
 [0.84284161 0.31479046 0.22723337 0.32735743 0.86195752 0.77143681
  0.72884336 0.60567263 0.29484131 0.70332368]
 [0.68006085 0.07906243 0.05091453 0.98405007 0.87172853 0.72408666
  0.71761532

#### 10. Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [18]:
d = np.random.random(30)
m = d.mean()
print(d)
print(m)

[0.65316127 0.84436269 0.33882696 0.93147276 0.08030239 0.81083116
 0.84727539 0.79894331 0.57822156 0.40239957 0.29506425 0.43941395
 0.42983662 0.59529306 0.62859093 0.24749321 0.59260947 0.50901046
 0.17327871 0.34589352 0.89697641 0.37276461 0.19472282 0.40482507
 0.38515047 0.24747462 0.07679691 0.63824683 0.9390757  0.81585697]
0.5171390548926971


#### 11. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [19]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 12. Перемножить матрицы 5x3 и 3x2

In [20]:
d = np.dot(np.ones((5,3)), np.ones((3,2)))
print(d)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 13. Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [33]:
d = np.arange(15)
print(d)
d[(3 < d) & (d < 8)] *= -1
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  1  2  3 -4 -5 -6 -7  8  9 10 11 12 13 14]


#### 14. Создать 5x5 матрицу со значениями в строках от 0 до 4

In [26]:
d = np.zeros((5,5))
d += np.arange(5)
print(d)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 15. Отнять среднее из каждой строки в матрице

In [28]:
d = np.random.rand(2, 3)
print(d)
e = d - d.mean(axis=1, keepdims=True)
print(e)

[[0.39869146 0.38290737 0.30434806]
 [0.81042676 0.42534933 0.41378208]]
[[ 0.03670916  0.02092507 -0.05763424]
 [ 0.26057404 -0.12450339 -0.13607065]]
